LOCALIZATION = {
    "en": {
        "welcome_message": "Welcome to FutureMentor! 🌟 I’m your personal mentor for planning and learning.\nWhat would you like to do?\n🎯 Create a goal\n📚 Add a study capsule\n💡 Get motivation\n🏆 View achievements\n🌍 Join a challenge\n🎮 Connect Habitica",
        "create_goal_title": "🎯 Enter the goal title (e.g., 'Pass IELTS'):",
        "create_goal_deadline": "Enter the deadline (dd.mm.yyyy):",
        "create_goal_message": "Write a motivational message to yourself (I’ll send it later):",
        "study_capsule_content": "📚 Add content for studying (e.g., English words, or send a video/image):",
        "study_capsule_send_date": "When should I remind you? (dd.mm.yyyy):",
        "motivation_message": "💡 You’re {progress}% towards your goal '{goal}'! {advice}",
        "achievement_earned": "🏆 You earned an achievement: '{achievement}'!",
        "challenge_joined": "You joined the challenge '{challenge}'! Good luck! 🍀",
        "add_step": "Enter the step title for goal '{goal}':",
        "recommend_course": "Recommended courses for '{goal}':\n{courses}",
        "set_mentor_style": "Choose mentor style: strict, friendly, or humorous",
        "group_goal_created": "Group goal '{title}' created! Invite friends with /invite_to_goal {goal_id}",
        "leaderboard": "🏆 Leaderboard:\n{leaderboard}",
        "strict_mentor_advice": "You’re lagging behind on '{goal}'! Focus and dedicate time daily!",
        "friendly_mentor_advice": "Great effort on '{goal}'! Keep it up, you’re doing awesome! 😊",
        "humorous_mentor_advice": "Hey, '{goal}' is waiting for you! Stop slacking, champ! 😜",
        "connect_habitica": "Enter your Habitica User ID and API Token (format: user_id:api_token):",
        "habitica_connected": "Habitica connected successfully! Tasks will sync with your goals.",
        "calendar_event_added": "Event '{event}' added to your calendar for {date}.",
        "test_result": "Test result: {correct}/{total} correct answers."
    },
    "ru": {
        "welcome_message": "Добро пожаловать в FutureMentor! 🌟 Я твой персональный наставник для планирования и обучения.\nЧто ты хочешь сделать?\n🎯 Создать цель\n📚 Добавить учебную капсулу\n💡 Получить мотивацию\n🏆 Посмотреть достижения\n🌍 Присоединиться к челленджу\n🎮 Подключить Habitica",
        "create_goal_title": "🎯 Введите название цели (например, 'Сдать IELTS'):",
        "create_goal_deadline": "Введите дедлайн (дд.мм.гггг):",
        "create_goal_message": "Напишите себе мотивационное сообщение (я отправлю его позже):",
        "study_capsule_content": "📚 Добавьте материал для обучения (например, английские слова, или отправьте видео/изображение):",
        "study_capsule_send_date": "Когда напомнить вам? (дд.мм.гггг):",
        "motivation_message": "💡 Вы достигли {progress}% вашей цели '{goal}'! {advice}",
        "achievement_earned": "🏆 Вы получили достижение: '{achievement}'!",
        "challenge_joined": "Вы присоединились к челленджу '{challenge}'! Удачи! 🍀",
        "add_step": "Введите название шага для цели '{goal}':",
        "recommend_course": "Рекомендуемые курсы для '{goal}':\n{courses}",
        "set_mentor_style": "Выберите стиль наставника: строгий, дружелюбный или юмористический",
        "group_goal_created": "Групповая цель '{title}' создана! Приглашайте друзей с /invite_to_goal {goal_id}",
        "leaderboard": "🏆 Таблица лидеров:\n{leaderboard}",
        "strict_mentor_advice": "Ты отстаёшь по цели '{goal}'! Сосредоточься и выделяй время каждый день!",
        "friendly_mentor_advice": "Отличная работа над '{goal}'! Продолжай, ты молодец! 😊",
        "humorous_mentor_advice": "Эй, '{goal}' ждёт тебя! Хватит лениться, чемпион! 😜",
        "connect_habitica": "Введите ваш User ID и API Token от Habitica (формат: user_id:api_token):",
        "habitica_connected": "Habitica успешно подключен! Задачи будут синхронизироваться с вашими целями.",
        "calendar_event_added": "Событие '{event}' добавлено в ваш календарь на {date}.",
        "test_result": "Результат теста: {correct}/{total} правильных ответов."
    }
}
